### ISSUE TITLE
KeyDb + RedisStack?  Can you make a dockerfile that merges redis/redis-stack with KeyDb?

### ISSUE THREAD

**Issue by VagyokC4** [pozetroninc/keydb-modules#2]
These templates for KeyDb are nice, but out of date.  Currently I am unable to get KeyDb working with the latest bits of redis/redis-stack.

Are you able to create an additional dockerfile where you bundle the latest versions of redis/redis-stack?  If so, can you please update?

Thanks

**Comment by neil-pozetroninc** [comment]
@VagyokC4 it would be best if you asked the @EQ-Alpha team for something official. Redis Stack is a big project and they might already have something on their roadmap.
